name: CI
on:
  push:
    branches: ['main']
  pull_request:
    branches: ['main']
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: pnpm/action-setup@v2
        with:
          version: 7.18.2
      - name: Install modules
        run: pnpm install
      - name: Run ESLint
        run: pnpm run lint
